<?php
/**
 * User: ruoning
 * Date: 2020/7/31
 * motto: 知行合一!
 */


namespace app\admin\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class AdminBase extends BaseController
{
    public $adminUser = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        // 判断是否登录
        if (empty($this->isLogin())) {
            return $this->redirect(url('login/index'), 302);
        }
        
    }

    public function isLogin()
    {
        $this->adminUser = session(config('admin.session_admin'));
        if (empty($this->adminUser)) {
            return false;
        }

        return true;
    }

    public function redirect(...$arge)
    {
        throw new HttpResponseException(redirect(...$arge));
    }
}